/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurante.view;

import javax.swing.JOptionPane;
import restaurante.Cliente;
import restaurante.Administrador;
import restaurante.Cadastrado;
/**
 *
 * @author janderson
 */
public class Cadastro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Cadastro.class.getName());

    /**
     * Creates new form Cadastro
     */
    public Cadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCadastrarSenha = new javax.swing.JPasswordField();
        txtCadastrarNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtCadastrarCpf = new javax.swing.JTextField();
        txtCadastrarEmail = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bttCadastrarFinalizar = new javax.swing.JButton();
        bttCadastrarBooleanADM = new javax.swing.JToggleButton();
        jLabel10 = new javax.swing.JLabel();

        jLabel6.setText("Digite seu nome:");

        jButton1.setText("jButton1");

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Bem vindo ao Restaurante");

        txtCadastrarSenha.addActionListener(this::txtCadastrarSenhaActionPerformed);

        txtCadastrarNome.addActionListener(this::txtCadastrarNomeActionPerformed);

        jLabel2.setText("Cadastre-se:");

        txtCadastrarCpf.addActionListener(this::txtCadastrarCpfActionPerformed);

        txtCadastrarEmail.addActionListener(this::txtCadastrarEmailActionPerformed);

        jLabel3.setText("Digite seu nome:");

        jLabel4.setText("Digite seu CPF  :");

        jLabel5.setText("Digite seu email :");

        jLabel7.setText("Digite sua senha:");

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 1, 50)); // NOI18N
        jLabel8.setText(" Cleber Lanches");

        bttCadastrarFinalizar.setText("Finalizar cadastro");
        bttCadastrarFinalizar.addActionListener(this::bttCadastrarFinalizarActionPerformed);

        bttCadastrarBooleanADM.setText("Sim");

        jLabel10.setText("Cadastrar com Admin?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(bttCadastrarFinalizar)
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bttCadastrarBooleanADM))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCadastrarEmail)
                                    .addComponent(txtCadastrarSenha)
                                    .addComponent(txtCadastrarNome)
                                    .addComponent(txtCadastrarCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(72, 72, 72)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel1)))
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCadastrarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCadastrarCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCadastrarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCadastrarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttCadastrarBooleanADM)
                    .addComponent(jLabel10))
                .addGap(13, 13, 13)
                .addComponent(bttCadastrarFinalizar)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCadastrarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadastrarSenhaActionPerformed

    }//GEN-LAST:event_txtCadastrarSenhaActionPerformed

    private void txtCadastrarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadastrarNomeActionPerformed

    }//GEN-LAST:event_txtCadastrarNomeActionPerformed

    private void txtCadastrarCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadastrarCpfActionPerformed

    }//GEN-LAST:event_txtCadastrarCpfActionPerformed

    private void txtCadastrarEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadastrarEmailActionPerformed

    }//GEN-LAST:event_txtCadastrarEmailActionPerformed

    private void bttCadastrarFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttCadastrarFinalizarActionPerformed
        if(txtCadastrarNome.getText().trim().isEmpty() ||
           txtCadastrarCpf.getText().trim().isEmpty() ||
           txtCadastrarEmail.getText().trim().isEmpty() ||
           txtCadastrarSenha.getPassword().length == 0){
        //erro: preencha todos os campos
        }
        else{
            boolean flag_repetido = false;
            for(Cadastrado usuario : Cadastrado.getListaCadastrados()){
                if(txtCadastrarNome.getText().equals(usuario.getNome())){
                    flag_repetido = true;
                }
            }
            if(flag_repetido == false){
                if(bttCadastrarBooleanADM.isSelected() == false){
                    Cliente c1 = new Cliente(txtCadastrarNome.getText(),
                                        txtCadastrarEmail.getText(), 
                                        txtCadastrarCpf.getText(), 
                                        txtCadastrarSenha.getPassword(),
                                        false);
                    this.dispose();
                }
                else{
                    Administrador ADM1 = new Administrador(txtCadastrarNome.getText(),
                                        txtCadastrarEmail.getText(), 
                                        txtCadastrarCpf.getText(), 
                                        txtCadastrarSenha.getPassword(),
                                        true);
                    this.dispose();
                }
            }
            else{
                //erro: nome ja utilizado
            }
        }

    }//GEN-LAST:event_bttCadastrarFinalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new Cadastro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton bttCadastrarBooleanADM;
    private javax.swing.JButton bttCadastrarFinalizar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCadastrarCpf;
    private javax.swing.JTextField txtCadastrarEmail;
    private javax.swing.JTextField txtCadastrarNome;
    private javax.swing.JPasswordField txtCadastrarSenha;
    // End of variables declaration//GEN-END:variables
}
