/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurante.view;

/**
 *
 * @author janderson
 */
public class InterfaceADMInicio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfaceADMInicio.class.getName());

    /**
     * Creates new form InterfaceADM
     */
    public InterfaceADMInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bttInicioADMGerenciarCozinha = new javax.swing.JButton();
        bttInicioADMMudarCardapio = new javax.swing.JButton();
        bttInicioADMHistoricos = new javax.swing.JButton();
        bttInicioADMAtualizarQtdMesas = new javax.swing.JButton();
        bttInicioADMDeslogar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ADM - Interface inicial");

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        jLabel1.setText("Bem vindo, Administrador (Nome)");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel2.setText("O que deseja fazer ?");

        bttInicioADMGerenciarCozinha.setText("Gerenciar a cozinha");

        bttInicioADMMudarCardapio.setText("Gerenciar itens do cardápio");

        bttInicioADMHistoricos.setText("Checar históricos do restaurante");

        bttInicioADMAtualizarQtdMesas.setText("Atualizar quantidade de mesas");

        bttInicioADMDeslogar.setText("Deslogar");
        bttInicioADMDeslogar.addActionListener(this::bttInicioADMDeslogarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttInicioADMAtualizarQtdMesas)
                    .addComponent(bttInicioADMHistoricos)
                    .addComponent(bttInicioADMMudarCardapio)
                    .addComponent(bttInicioADMGerenciarCozinha)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bttInicioADMDeslogar)
                        .addGap(45, 45, 45))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bttInicioADMGerenciarCozinha)
                .addGap(18, 18, 18)
                .addComponent(bttInicioADMMudarCardapio)
                .addGap(18, 18, 18)
                .addComponent(bttInicioADMAtualizarQtdMesas)
                .addGap(18, 18, 18)
                .addComponent(bttInicioADMHistoricos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(bttInicioADMDeslogar)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttInicioADMDeslogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttInicioADMDeslogarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttInicioADMDeslogarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfaceADMInicio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttInicioADMAtualizarQtdMesas;
    private javax.swing.JButton bttInicioADMDeslogar;
    private javax.swing.JButton bttInicioADMGerenciarCozinha;
    private javax.swing.JButton bttInicioADMHistoricos;
    private javax.swing.JButton bttInicioADMMudarCardapio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
