/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurante.view;
import javax.swing.JOptionPane;
import restaurante.Cliente;

/**
 *
 * @author janderson
 */
public class InterfaceClienteInicio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfaceClienteInicio.class.getName());
    
    private Cliente usuarioLogado;
    /**
     * Creates new form InterfaceCliente
     */
    public InterfaceClienteInicio(Cliente pessoaLogada) {
        initComponents();
        
        this.usuarioLogado = pessoaLogada;
        if (usuarioLogado != null) {
            TextoMenuInicial.setText("Bem vindo, Cliente " + usuarioLogado.getNome() + "!");
        } else {
            TextoMenuInicial.setText("Bem vindo, Cliente (Modo de Teste)!");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraTarefas = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        bttClienteInicioDeslogar = new javax.swing.JButton();
        TextoMenuInicial = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bttClienteInicioAtendimento = new javax.swing.JButton();
        bttClienteInicioHistorico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cliente - Interface inicial");

        bttClienteInicioDeslogar.setText("Deslogar");
        bttClienteInicioDeslogar.addActionListener(this::bttClienteInicioDeslogarActionPerformed);

        TextoMenuInicial.setFont(new java.awt.Font("Liberation Sans", 1, 28)); // NOI18N
        TextoMenuInicial.setText("Bem vindo, Cliente (Nome)");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel3.setText("O que deseja realizar hoje ?");

        bttClienteInicioAtendimento.setText("Iniciar atendimento");
        bttClienteInicioAtendimento.addActionListener(this::bttClienteInicioAtendimentoActionPerformed);

        bttClienteInicioHistorico.setText("Checar historico ");
        bttClienteInicioHistorico.addActionListener(this::bttClienteInicioHistoricoActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextoMenuInicial)
                    .addComponent(bttClienteInicioDeslogar)
                    .addComponent(jLabel3)
                    .addComponent(bttClienteInicioAtendimento)
                    .addComponent(bttClienteInicioHistorico))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(TextoMenuInicial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(44, 44, 44)
                .addComponent(bttClienteInicioAtendimento)
                .addGap(18, 18, 18)
                .addComponent(bttClienteInicioHistorico)
                .addGap(73, 73, 73)
                .addComponent(bttClienteInicioDeslogar)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        BarraTarefas.addTab("Menu", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BarraTarefas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BarraTarefas, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttClienteInicioAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttClienteInicioAtendimentoActionPerformed
        if(usuarioLogado.getContaAtual() == null){
            usuarioLogado.escolherMesa();
            PanelClienteMesa clientemesa = new PanelClienteMesa(usuarioLogado, BarraTarefas);
            BarraTarefas.addTab("Seleção da mesa", clientemesa);
            BarraTarefas.setSelectedIndex(BarraTarefas.getTabCount() - 1);
        }
        else{
            //conta em aberto;
        }
    }//GEN-LAST:event_bttClienteInicioAtendimentoActionPerformed

    private void bttClienteInicioDeslogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttClienteInicioDeslogarActionPerformed
        if(usuarioLogado.getContaAtual() != null){
            //mensagem de erro: você ainda possui contas em aberto.
        }
        else{
            this.dispose();
        }
    }//GEN-LAST:event_bttClienteInicioDeslogarActionPerformed

    private void bttClienteInicioHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttClienteInicioHistoricoActionPerformed
        PanelClienteHistorico clientehistorico = new PanelClienteHistorico(usuarioLogado, BarraTarefas);
            BarraTarefas.addTab("Historico cliente", clientehistorico);
            BarraTarefas.setSelectedIndex(BarraTarefas.getTabCount() - 1);
    }//GEN-LAST:event_bttClienteInicioHistoricoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfaceClienteInicio(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane BarraTarefas;
    private javax.swing.JLabel TextoMenuInicial;
    private javax.swing.JButton bttClienteInicioAtendimento;
    private javax.swing.JButton bttClienteInicioDeslogar;
    private javax.swing.JButton bttClienteInicioHistorico;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
