/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurante.view;
import restaurante.Administrador;
/**
 *
 * @author janderson
 */
public class InterfaceADMInicio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfaceADMInicio.class.getName());
    
    private Administrador usuarioLogado;
    /**
     * Creates new form InterfaceADM
     */
    public InterfaceADMInicio(Administrador pessoaLogada) {
        initComponents();
        this.usuarioLogado = pessoaLogada;
        lblADMInicio.setText("Bem vindo, Administrador" + usuarioLogado.getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraTarefas = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        bttInicioADMGerenciarCozinha = new javax.swing.JButton();
        bttInicioADMMudarCardapio = new javax.swing.JButton();
        bttInicioADMHistoricos = new javax.swing.JButton();
        bttInicioADMAtualizarQtdMesas = new javax.swing.JButton();
        bttInicioADMDeslogar1 = new javax.swing.JButton();
        lblADMInicio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ADM - Interface inicial");

        BarraTarefas.setPreferredSize(new java.awt.Dimension(600, 600));

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel3.setText("O que deseja fazer ?");

        bttInicioADMGerenciarCozinha.setText("Gerenciar a cozinha");
        bttInicioADMGerenciarCozinha.addActionListener(this::bttInicioADMGerenciarCozinhaActionPerformed);

        bttInicioADMMudarCardapio.setText("Gerenciar itens do cardápio");
        bttInicioADMMudarCardapio.addActionListener(this::bttInicioADMMudarCardapioActionPerformed);

        bttInicioADMHistoricos.setText("Checar históricos do restaurante");
        bttInicioADMHistoricos.addActionListener(this::bttInicioADMHistoricosActionPerformed);

        bttInicioADMAtualizarQtdMesas.setText("Atualizar quantidade de mesas");
        bttInicioADMAtualizarQtdMesas.addActionListener(this::bttInicioADMAtualizarQtdMesasActionPerformed);

        bttInicioADMDeslogar1.setText("Deslogar");
        bttInicioADMDeslogar1.addActionListener(this::bttInicioADMDeslogar1ActionPerformed);

        lblADMInicio.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        lblADMInicio.setText("Bem vindo, Administrador (Nome)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttInicioADMAtualizarQtdMesas)
                    .addComponent(bttInicioADMHistoricos)
                    .addComponent(bttInicioADMMudarCardapio)
                    .addComponent(bttInicioADMGerenciarCozinha)
                    .addComponent(jLabel3)
                    .addComponent(lblADMInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bttInicioADMDeslogar1)
                .addGap(62, 62, 62))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(lblADMInicio)
                .addGap(43, 43, 43)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bttInicioADMGerenciarCozinha)
                .addGap(18, 18, 18)
                .addComponent(bttInicioADMMudarCardapio)
                .addGap(18, 18, 18)
                .addComponent(bttInicioADMAtualizarQtdMesas)
                .addGap(18, 18, 18)
                .addComponent(bttInicioADMHistoricos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttInicioADMDeslogar1)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        BarraTarefas.addTab("Menu", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BarraTarefas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(BarraTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttInicioADMDeslogar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttInicioADMDeslogar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttInicioADMDeslogar1ActionPerformed

    private void bttInicioADMGerenciarCozinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttInicioADMGerenciarCozinhaActionPerformed
        PanelADMCozinha cozinha = new PanelADMCozinha(usuarioLogado, BarraTarefas);
        
        BarraTarefas.addTab("Cozinha", cozinha);
        BarraTarefas.setSelectedIndex(BarraTarefas.getTabCount() - 1);
    }//GEN-LAST:event_bttInicioADMGerenciarCozinhaActionPerformed

    private void bttInicioADMMudarCardapioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttInicioADMMudarCardapioActionPerformed
        PanelADMCardapio cardapio = new PanelADMCardapio(usuarioLogado, BarraTarefas);
        
        BarraTarefas.addTab("Cardápio", cardapio);
        BarraTarefas.setSelectedIndex(BarraTarefas.getTabCount() - 1);
    }//GEN-LAST:event_bttInicioADMMudarCardapioActionPerformed

    private void bttInicioADMAtualizarQtdMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttInicioADMAtualizarQtdMesasActionPerformed
        PanelADMMesas mesa = new PanelADMMesas(usuarioLogado, BarraTarefas);
        
        BarraTarefas.addTab("Mudar mesa", mesa);
        BarraTarefas.setSelectedIndex(BarraTarefas.getTabCount() - 1);
        
    }//GEN-LAST:event_bttInicioADMAtualizarQtdMesasActionPerformed

    private void bttInicioADMHistoricosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttInicioADMHistoricosActionPerformed
        PanelADMChecarHistoricos historico = new PanelADMChecarHistoricos(usuarioLogado, BarraTarefas);
        
        BarraTarefas.addTab("Históricos", historico);
        BarraTarefas.setSelectedIndex(BarraTarefas.getTabCount() - 1);
    }//GEN-LAST:event_bttInicioADMHistoricosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfaceADMInicio(null).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane BarraTarefas;
    private javax.swing.JButton bttInicioADMAtualizarQtdMesas;
    private javax.swing.JButton bttInicioADMDeslogar1;
    private javax.swing.JButton bttInicioADMGerenciarCozinha;
    private javax.swing.JButton bttInicioADMHistoricos;
    private javax.swing.JButton bttInicioADMMudarCardapio;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblADMInicio;
    // End of variables declaration//GEN-END:variables
}
