/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package restaurante.view;

import restaurante.Cliente;

/**
 *
 * @author janderson
 */
public class PanelVisualizarContaCliente extends javax.swing.JPanel {

    private javax.swing.JTabbedPane BarraTarefas;
    private Cliente usuarioLogado;
    
    public PanelVisualizarContaCliente(Cliente pessoaLogada, javax.swing.JTabbedPane BarraTarefas) {
        initComponents();
        this.BarraTarefas = BarraTarefas;
        this.usuarioLogado = pessoaLogada;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVisualizarContaCliente = new javax.swing.JTable();
        bttVisualizadorContaFechar = new javax.swing.JButton();
        lblVisualizarContaCliente = new javax.swing.JLabel();

        tblVisualizarContaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº da mesa", "Itens do pedido", "Status", "Custo total"
            }
        ));
        jScrollPane1.setViewportView(tblVisualizarContaCliente);

        bttVisualizadorContaFechar.setText("Fechar");
        bttVisualizadorContaFechar.addActionListener(this::bttVisualizadorContaFecharActionPerformed);

        lblVisualizarContaCliente.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lblVisualizarContaCliente.setText("Visualizar conta de (nome)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(bttVisualizadorContaFechar)
                .addGap(32, 32, 32)
                .addComponent(lblVisualizarContaCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttVisualizadorContaFechar)
                    .addComponent(lblVisualizarContaCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttVisualizadorContaFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttVisualizadorContaFecharActionPerformed
        BarraTarefas.setSelectedIndex(BarraTarefas.getTabCount() - 1);
        BarraTarefas.remove(this);
    }//GEN-LAST:event_bttVisualizadorContaFecharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttVisualizadorContaFechar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblVisualizarContaCliente;
    private javax.swing.JTable tblVisualizarContaCliente;
    // End of variables declaration//GEN-END:variables
}
