/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package restaurante.view;

import javax.swing.table.DefaultTableModel;
import restaurante.Cliente;
import restaurante.Conta;

/**
 *
 * @author janderson
 */
public class PanelClienteHistorico extends javax.swing.JPanel {

    private javax.swing.JTabbedPane BarraTarefas;
    private Cliente usuarioLogado;
    
    public PanelClienteHistorico(Cliente pessoaLogada, javax.swing.JTabbedPane BarraTarefas) {
        initComponents();
        this.BarraTarefas = BarraTarefas;
        this.usuarioLogado = pessoaLogada;
        
        lblVisualizarHistoricoCliente.setText("Historico de atividade de" + pessoaLogada.getNome());
        
        DefaultTableModel TabelaVisualizarHistoricoCliente = (DefaultTableModel) tblVisualizarHistoricoCliente.getModel(); 
        //nº mesa da conta, nº de pedidos, Status, Custo Total
        //vai na lista de contas do cliente, pega os valore da conta
        for(Conta existente : usuarioLogado.getHistoricoCliente()){
            Object[] contaCliente = new Object[]{existente, existente.getQtdPedidos(), existente.getStatusConta(), existente.getTotalConta()};
            TabelaVisualizarHistoricoCliente.addRow(contaCliente);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bttVisualizarPedidoVisualizar = new javax.swing.JButton();
        bttHistoricoClienteFechar = new javax.swing.JButton();
        lblVisualizarHistoricoCliente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVisualizarHistoricoCliente = new javax.swing.JTable();
        bttVisualizaHistoricoVisualizar = new javax.swing.JButton();

        bttVisualizarPedidoVisualizar.setText("Visualizar");

        bttHistoricoClienteFechar.setText("Fechar");
        bttHistoricoClienteFechar.addActionListener(this::bttHistoricoClienteFecharActionPerformed);

        lblVisualizarHistoricoCliente.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lblVisualizarHistoricoCliente.setText("Historico de atividade de (nome)");

        tblVisualizarHistoricoCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº da conta", "Nº de pedidos", "Status", "Custo total"
            }
        ));
        jScrollPane1.setViewportView(tblVisualizarHistoricoCliente);

        bttVisualizaHistoricoVisualizar.setText("Visualizar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(bttHistoricoClienteFechar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblVisualizarHistoricoCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttVisualizaHistoricoVisualizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttHistoricoClienteFechar)
                    .addComponent(lblVisualizarHistoricoCliente)
                    .addComponent(bttVisualizaHistoricoVisualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttHistoricoClienteFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttHistoricoClienteFecharActionPerformed
        BarraTarefas.setSelectedIndex(BarraTarefas.getTabCount() - 1);
        BarraTarefas.remove(this);
    }//GEN-LAST:event_bttHistoricoClienteFecharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttHistoricoClienteFechar;
    private javax.swing.JButton bttVisualizaHistoricoVisualizar;
    private javax.swing.JButton bttVisualizarPedidoVisualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblVisualizarHistoricoCliente;
    private javax.swing.JTable tblVisualizarHistoricoCliente;
    // End of variables declaration//GEN-END:variables
}
