/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package restaurante.view;

import restaurante.Cliente;
import restaurante.Conta;

/**
 *
 * @author janderson
 */
public class PanelVisualizarPedidoGenerico extends javax.swing.JPanel {

    private javax.swing.JTabbedPane BarraTarefas;
    private Cliente usuarioLogado;
    
    public PanelVisualizarPedidoGenerico(Cliente pessoaLogada, javax.swing.JTabbedPane BarraTarefas) {
        initComponents();
 
        
        this.BarraTarefas = BarraTarefas;
        this.usuarioLogado = pessoaLogada;
        
        //for(Pedido item : )} vai ter que ser um for utilizando 
        //uma lista de contas que será criada em cozinha, já que 
        //não podemos pegar a conta diretamente por usuarioLogado.getContaAtual, 
        //uma vez que ele pode não estar mais apontando para a conta.
        //portanto, é necessário:
        //1. criar uma lista de contas na cozinha
        //2. fazer as contas serem adicionadas nela
        //3. criar uma metodo que procure e retorne contas de um cliente 
        //especifico        
        //4.achar a conta especifica que se está analisando
        //pera, esse visualizador será sempre aberto a partir de 
        //alguma tabela.
        //é só pegar o Pedido da tabela e receber pelo construtor
        //mas e quanto a conta ? para conta, teremos que fazer o esquema
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVisualizarPedido = new javax.swing.JTable();
        bttVisualizadorPedidoFechar = new javax.swing.JButton();
        lblVisualizarPedidoCliente = new javax.swing.JLabel();

        tblVisualizarPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item pedido", "Quantidade", "Status", "Custo total"
            }
        ));
        jScrollPane1.setViewportView(tblVisualizarPedido);

        bttVisualizadorPedidoFechar.setText("Fechar");
        bttVisualizadorPedidoFechar.addActionListener(this::bttVisualizadorPedidoFecharActionPerformed);

        lblVisualizarPedidoCliente.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lblVisualizarPedidoCliente.setText("Visualizar pedido de (nome)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(bttVisualizadorPedidoFechar)
                .addGap(18, 18, 18)
                .addComponent(lblVisualizarPedidoCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttVisualizadorPedidoFechar)
                    .addComponent(lblVisualizarPedidoCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttVisualizadorPedidoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttVisualizadorPedidoFecharActionPerformed
        BarraTarefas.setSelectedIndex(BarraTarefas.getTabCount() - 1);
        BarraTarefas.remove(this);
    }//GEN-LAST:event_bttVisualizadorPedidoFecharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttVisualizadorPedidoFechar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblVisualizarPedidoCliente;
    private javax.swing.JTable tblVisualizarPedido;
    // End of variables declaration//GEN-END:variables
}
