/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package restaurante.view;

import javax.swing.table.DefaultTableModel;
import restaurante.Cardapio;
import restaurante.Cliente;
import restaurante.Conta;
import restaurante.Pedido;
/**
 *
 * @author janderson e marcelo livros
 */
public class PanelVisualizarContaCliente extends javax.swing.JPanel {

    private javax.swing.JTabbedPane BarraTarefas;
    private Cliente usuarioLogado;
    private Conta contaCliente;
    
    public PanelVisualizarContaCliente(Cliente pessoaLogada, javax.swing.JTabbedPane BarraTarefas, Conta vista) {
        initComponents();
        this.BarraTarefas = BarraTarefas;
        this.usuarioLogado = pessoaLogada;
        this.contaCliente = vista;
        
        lblVisualizarContaCliente.setText("Visualizar conta de " + usuarioLogado.getNome());
        //objeto tem que ter n pedido, n pedidos feitos, status atual e Custo total
        DefaultTableModel TabelaVisualizarContaCliente = (DefaultTableModel) tblVisualizarContaCliente.getModel();
        int cont = 0;
        for(Pedido item : contaCliente.getListaPedidosCliente()){
            cont ++;
            item.setOrdem(cont);

            Object[] contaVista = new Object[]{item, item.calcularQtdProdutos(), item.getStatus(), "$" + item.getTotal()};
            TabelaVisualizarContaCliente.addRow(contaVista);
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVisualizarContaCliente = new javax.swing.JTable();
        bttVisualizadorContaFechar = new javax.swing.JButton();
        lblVisualizarContaCliente = new javax.swing.JLabel();
        bttVisualizarContaVisualizar = new javax.swing.JButton();

        tblVisualizarContaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº do pedido", "Itens no pedido", "Status", "Custo total"
            }
        ));
        jScrollPane1.setViewportView(tblVisualizarContaCliente);

        bttVisualizadorContaFechar.setText("Fechar");
        bttVisualizadorContaFechar.addActionListener(this::bttVisualizadorContaFecharActionPerformed);

        lblVisualizarContaCliente.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lblVisualizarContaCliente.setText("Visualizar conta de (nome)");

        bttVisualizarContaVisualizar.setText("Visualizar");
        bttVisualizarContaVisualizar.addActionListener(this::bttVisualizarContaVisualizarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(bttVisualizadorContaFechar)
                .addGap(32, 32, 32)
                .addComponent(lblVisualizarContaCliente)
                .addGap(18, 18, 18)
                .addComponent(bttVisualizarContaVisualizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttVisualizadorContaFechar)
                    .addComponent(lblVisualizarContaCliente)
                    .addComponent(bttVisualizarContaVisualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttVisualizadorContaFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttVisualizadorContaFecharActionPerformed
        BarraTarefas.setSelectedIndex(BarraTarefas.getTabCount() - 1);
        BarraTarefas.remove(this);
    }//GEN-LAST:event_bttVisualizadorContaFecharActionPerformed

    private void bttVisualizarContaVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttVisualizarContaVisualizarActionPerformed
        int linhaSelecionada = tblVisualizarContaCliente.getSelectedRow();
        if(linhaSelecionada != -1){
            Pedido visto = (Pedido) tblVisualizarContaCliente.getValueAt(linhaSelecionada, 0);
            PanelVisualizarPedidoGenerico pedidocliente = new PanelVisualizarPedidoGenerico(usuarioLogado, BarraTarefas, visto);
            BarraTarefas.addTab("Visualizar pedido", pedidocliente);
            BarraTarefas.setSelectedIndex(BarraTarefas.getTabCount() - 1);
        }
        else{
            //erro nenhum pedido selecionado
        }
    }//GEN-LAST:event_bttVisualizarContaVisualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttVisualizadorContaFechar;
    private javax.swing.JButton bttVisualizarContaVisualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblVisualizarContaCliente;
    private javax.swing.JTable tblVisualizarContaCliente;
    // End of variables declaration//GEN-END:variables
}
