/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package restaurante.view;

import java.util.Arrays;
import javax.swing.JOptionPane;
import restaurante.Administrador;
import restaurante.Mesa;

/**
 *
 * @author janderson
 */
public class PanelADMMesas extends javax.swing.JPanel {

    private javax.swing.JTabbedPane BarraTarefas;
    private Administrador usuarioLogado;
    
    public PanelADMMesas(Administrador pessoaLogada, javax.swing.JTabbedPane BarraTarefas) {
        initComponents();
        this.BarraTarefas = BarraTarefas;
        this.usuarioLogado = pessoaLogada;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtADMMesasAtualizar = new javax.swing.JTextField();
        bttADMMesaConfirmar = new javax.swing.JButton();
        bttADMMesaEncerrar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 30)); // NOI18N
        jLabel1.setText("Atualizar quantidade de mesas");

        jLabel2.setText("Aviso: Fazer isso modificará não alterará as mesas atuais dos clientes.");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel3.setText("Insira o numero que atualizará a quantidade de mesas:");

        txtADMMesasAtualizar.addActionListener(this::txtADMMesasAtualizarActionPerformed);

        bttADMMesaConfirmar.setText("Confirmar");
        bttADMMesaConfirmar.addActionListener(this::bttADMMesaConfirmarActionPerformed);

        bttADMMesaEncerrar.setText("Encerrar atividades");
        bttADMMesaEncerrar.addActionListener(this::bttADMMesaEncerrarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(txtADMMesasAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(bttADMMesaConfirmar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(bttADMMesaEncerrar)))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtADMMesasAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttADMMesaConfirmar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(bttADMMesaEncerrar)
                .addGap(133, 133, 133))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtADMMesasAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtADMMesasAtualizarActionPerformed
        
    }//GEN-LAST:event_txtADMMesasAtualizarActionPerformed

    private void bttADMMesaConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttADMMesaConfirmarActionPerformed
        if(txtADMMesasAtualizar.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Preencha número de mesas");
            return;
        }
        if (!txtADMMesasAtualizar.getText().matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Digite apenas números.");
            return;
        }
        
        String mesasString = txtADMMesasAtualizar.getText();
        int nMesas = Integer.parseInt(mesasString);
        Mesa.setQtdMesa(nMesas);
        JOptionPane.showMessageDialog(this, "Atualizado número de mesas: " + nMesas);
        System.out.println("Quantidade de mesas: " + Mesa.getQtdMesa());
    }//GEN-LAST:event_bttADMMesaConfirmarActionPerformed

    private void bttADMMesaEncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttADMMesaEncerrarActionPerformed
        BarraTarefas.remove(this);
    }//GEN-LAST:event_bttADMMesaEncerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttADMMesaConfirmar;
    private javax.swing.JButton bttADMMesaEncerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtADMMesasAtualizar;
    // End of variables declaration//GEN-END:variables
}
