
package restaurante.view;

import restaurante.Administrador;
import restaurante.Cadastrado;
import restaurante.Cliente;

/**
 *
 * @author janderson
 */
public class PanelADMHistoricoCliente extends javax.swing.JPanel {

    private javax.swing.JTabbedPane BarraTarefas;
    private Administrador usuarioLogado;
    
    public PanelADMHistoricoCliente(Administrador pessoaLogada, javax.swing.JTabbedPane BarraTarefas) {
        initComponents();
        this.BarraTarefas = BarraTarefas;
        this.usuarioLogado = pessoaLogada;
        
        for(Cadastrado usuario : Cadastrado.getListaCadastrados()){
            if(usuario instanceof Cliente){
                cbxADMHistoricoCliente.addItem(usuario);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbxADMHistoricoCliente = new javax.swing.JComboBox<>();
        bttADMHistoricoClienteConfirmar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bttADMHistoricoClienteContas = new javax.swing.JButton();
        lblADMHistoricoClienteNome = new javax.swing.JLabel();
        lblADMHistoricoClienteEmail = new javax.swing.JLabel();
        lblADMHistoricoClienteCpf = new javax.swing.JLabel();
        bttADMHistoricoClienteVoltar = new javax.swing.JButton();

        cbxADMHistoricoCliente.addActionListener(this::cbxADMHistoricoClienteActionPerformed);

        bttADMHistoricoClienteConfirmar.setText("Confirmar");
        bttADMHistoricoClienteConfirmar.addActionListener(this::bttADMHistoricoClienteConfirmarActionPerformed);

        jLabel1.setText("Nome:");

        jLabel2.setText("Email:");

        jLabel3.setText("CPF:");

        bttADMHistoricoClienteContas.setText("Visualizar Historico de contas");
        bttADMHistoricoClienteContas.addActionListener(this::bttADMHistoricoClienteContasActionPerformed);

        bttADMHistoricoClienteVoltar.setText("Voltar");
        bttADMHistoricoClienteVoltar.addActionListener(this::bttADMHistoricoClienteVoltarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bttADMHistoricoClienteVoltar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cbxADMHistoricoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(bttADMHistoricoClienteConfirmar))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(bttADMHistoricoClienteContas))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblADMHistoricoClienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblADMHistoricoClienteEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblADMHistoricoClienteCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxADMHistoricoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttADMHistoricoClienteConfirmar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                        .addGap(43, 43, 43)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                        .addGap(64, 64, 64))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(lblADMHistoricoClienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(lblADMHistoricoClienteEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblADMHistoricoClienteCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(bttADMHistoricoClienteContas)
                .addGap(88, 88, 88)
                .addComponent(bttADMHistoricoClienteVoltar)
                .addGap(87, 87, 87))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbxADMHistoricoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxADMHistoricoClienteActionPerformed
        
    }//GEN-LAST:event_cbxADMHistoricoClienteActionPerformed

    private void bttADMHistoricoClienteVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttADMHistoricoClienteVoltarActionPerformed
        PanelADMChecarHistoricos historico = new PanelADMChecarHistoricos(usuarioLogado, BarraTarefas);
        
        BarraTarefas.addTab("Históricos", historico);
        BarraTarefas.setSelectedIndex(BarraTarefas.getTabCount() - 1);
        BarraTarefas.remove(this);
    }//GEN-LAST:event_bttADMHistoricoClienteVoltarActionPerformed

    private void bttADMHistoricoClienteConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttADMHistoricoClienteConfirmarActionPerformed
        Cliente pesquisado = (Cliente) cbxADMHistoricoCliente.getSelectedItem();
        
        lblADMHistoricoClienteNome.setText(pesquisado.getNome());
        lblADMHistoricoClienteEmail.setText(pesquisado.getEmail());
        lblADMHistoricoClienteCpf.setText(pesquisado.getCpf());
    }//GEN-LAST:event_bttADMHistoricoClienteConfirmarActionPerformed

    private void bttADMHistoricoClienteContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttADMHistoricoClienteContasActionPerformed
        Cliente pesquisado = (Cliente) cbxADMHistoricoCliente.getSelectedItem();
        PanelClienteHistorico historico = new PanelClienteHistorico(pesquisado, BarraTarefas);
        
        BarraTarefas.addTab("Historico " + pesquisado.getNome(), historico);
        BarraTarefas.setSelectedIndex(BarraTarefas.getTabCount() - 1);
        BarraTarefas.remove(this);
    }//GEN-LAST:event_bttADMHistoricoClienteContasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttADMHistoricoClienteConfirmar;
    private javax.swing.JButton bttADMHistoricoClienteContas;
    private javax.swing.JButton bttADMHistoricoClienteVoltar;
    private javax.swing.JComboBox<Cadastrado> cbxADMHistoricoCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblADMHistoricoClienteCpf;
    private javax.swing.JLabel lblADMHistoricoClienteEmail;
    private javax.swing.JLabel lblADMHistoricoClienteNome;
    // End of variables declaration//GEN-END:variables
}
