/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package restaurante.view;

import restaurante.Cliente;

/**
 *
 * @author janderson
 */
public class PanelClientePagamentoConta extends javax.swing.JPanel {

    private javax.swing.JTabbedPane BarraTarefas;
    private Cliente usuarioLogado;
    
    public PanelClientePagamentoConta(Cliente pessoaLogada, javax.swing.JTabbedPane BarraTarefas) {
        initComponents();
        this.BarraTarefas = BarraTarefas;
        this.usuarioLogado = pessoaLogada;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bttClienteContaVisualizarPedido = new javax.swing.JButton();
        bttClienteContaPagar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        bttClienteContaNovoPedido = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        jLabel1.setText("Sua conta atual:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Pedido", "Status", "Custo"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        bttClienteContaVisualizarPedido.setText("Visualizar");
        bttClienteContaVisualizarPedido.addActionListener(this::bttClienteContaVisualizarPedidoActionPerformed);

        bttClienteContaPagar.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        bttClienteContaPagar.setText("Pagar");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel2.setText("Deseja fazer um novo pedido ?");

        bttClienteContaNovoPedido.setText("Fazer novo pedido!");
        bttClienteContaNovoPedido.addActionListener(this::bttClienteContaNovoPedidoActionPerformed);

        jLabel3.setText("Obs: Enquanto seu pedido não for entregue, você pode desfaze-lo!");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel4.setText("Selecione metodo de pagamento:");

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel5.setText("Total: (valor)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bttClienteContaNovoPedido)))))
                        .addGap(12, 12, 12)
                        .addComponent(bttClienteContaVisualizarPedido))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bttClienteContaPagar)))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bttClienteContaVisualizarPedido)
                .addGap(113, 113, 113)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttClienteContaPagar)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttClienteContaNovoPedido)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addContainerGap(80, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttClienteContaVisualizarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttClienteContaVisualizarPedidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttClienteContaVisualizarPedidoActionPerformed

    private void bttClienteContaNovoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttClienteContaNovoPedidoActionPerformed
        PanelClientePedido novopedido = new PanelClientePedido(usuarioLogado, BarraTarefas);
        
        BarraTarefas.addTab("Novo pedido", novopedido);
        BarraTarefas.setSelectedIndex(BarraTarefas.getTabCount() - 1);
        
    }//GEN-LAST:event_bttClienteContaNovoPedidoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttClienteContaNovoPedido;
    private javax.swing.JButton bttClienteContaPagar;
    private javax.swing.JButton bttClienteContaVisualizarPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
