/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package restaurante.view;

import javax.swing.table.DefaultTableModel;
import restaurante.Cliente;
import restaurante.Conta;
import restaurante.Pedido;
import restaurante.Cardapio;
import restaurante.Comida;
import restaurante.Bebida;
        
/**
 *
 * @author janderson
 */
public class PanelVisualizarPedidoGenerico extends javax.swing.JPanel {

    private javax.swing.JTabbedPane BarraTarefas;
    private Cliente usuarioLogado;
    private Pedido pedidoVisto;
    
    public PanelVisualizarPedidoGenerico(Cliente pessoaLogada, javax.swing.JTabbedPane BarraTarefas, Pedido visto) {
        initComponents();
        this.BarraTarefas = BarraTarefas;
        this.usuarioLogado = pessoaLogada;
        this.pedidoVisto =  visto;
        
        DefaultTableModel TabelaVisualizarPedido = (DefaultTableModel)tblVisualizarPedido.getModel();
        
        int cont = 0;
        for(Cardapio item : visto.getListaItensSolicitados()){
            Object[] itenspedidos = new Object[]{item, visto.getQtdSolicitada().get(cont), visto.getStatus(), visto.getTotal()};
            TabelaVisualizarPedido.addRow(itenspedidos); 
            cont++;
        }
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVisualizarPedido = new javax.swing.JTable();
        bttVisualizadorPedidoFechar = new javax.swing.JButton();
        lblVisualizarPedidoCliente = new javax.swing.JLabel();
        bttVisualizarPedidoVisualizar = new javax.swing.JButton();

        tblVisualizarPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item pedido", "Quantidade", "Status", "Custo total"
            }
        ));
        jScrollPane1.setViewportView(tblVisualizarPedido);

        bttVisualizadorPedidoFechar.setText("Fechar");
        bttVisualizadorPedidoFechar.addActionListener(this::bttVisualizadorPedidoFecharActionPerformed);

        lblVisualizarPedidoCliente.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lblVisualizarPedidoCliente.setText("Visualizar pedido de (nome)");

        bttVisualizarPedidoVisualizar.setText("Visualizar");
        bttVisualizarPedidoVisualizar.addActionListener(this::bttVisualizarPedidoVisualizarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(bttVisualizadorPedidoFechar)
                .addGap(18, 18, 18)
                .addComponent(lblVisualizarPedidoCliente)
                .addGap(18, 18, 18)
                .addComponent(bttVisualizarPedidoVisualizar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttVisualizadorPedidoFechar)
                    .addComponent(lblVisualizarPedidoCliente)
                    .addComponent(bttVisualizarPedidoVisualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttVisualizadorPedidoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttVisualizadorPedidoFecharActionPerformed
        BarraTarefas.setSelectedIndex(BarraTarefas.getTabCount() - 1);
        BarraTarefas.remove(this);
    }//GEN-LAST:event_bttVisualizadorPedidoFecharActionPerformed

    private void bttVisualizarPedidoVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttVisualizarPedidoVisualizarActionPerformed
        int linhaSelecionada = tblVisualizarPedido.getSelectedRow();
        if(linhaSelecionada != -1){
            Cardapio itemGenerico = (Cardapio) tblVisualizarPedido.getValueAt(linhaSelecionada, 0);
            if(itemGenerico instanceof Comida){ //item = comida
                PanelVisualizarCardapioComidaGenerico pn = new PanelVisualizarCardapioComidaGenerico(usuarioLogado, BarraTarefas,(Comida) itemGenerico);
                BarraTarefas.addTab("Visualizar pedido", pn);
            }
            else{ //item = bebida
                PanelVisualizarCardapioBebidaGenerico pn = new PanelVisualizarCardapioBebidaGenerico(usuarioLogado, BarraTarefas,(Bebida) itemGenerico);
                BarraTarefas.addTab("Visualizar pedido", pn);
            }
        }
        else{
            //erro nenhum pedido selecionado
        }
    }//GEN-LAST:event_bttVisualizarPedidoVisualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttVisualizadorPedidoFechar;
    private javax.swing.JButton bttVisualizarPedidoVisualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblVisualizarPedidoCliente;
    private javax.swing.JTable tblVisualizarPedido;
    // End of variables declaration//GEN-END:variables
}
