/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package restaurante.view;


import restaurante.Cadastrado;
import restaurante.Bebida;


/**
 *
 * @author janderson
 */
public class PanelVisualizarCardapioBebidaGenerico extends javax.swing.JPanel {

    private javax.swing.JTabbedPane BarraTarefas;
    private Cadastrado usuarioLogado;
    private Bebida bebidaVisualizada;
    
    public PanelVisualizarCardapioBebidaGenerico(Cadastrado pessoaLogada, javax.swing.JTabbedPane BarraTarefas, Bebida vista) {
        initComponents();
        this.BarraTarefas = BarraTarefas;
        this.usuarioLogado = pessoaLogada;
        this.bebidaVisualizada = vista;
        
        lblVisualizarBebida.setText("Visualizar " + bebidaVisualizada.getNome());
        lblVisualizarBebidaNome.setText(bebidaVisualizada.getNome());
        lblVisualizarBebidaCusto.setText("$" + String.valueOf(bebidaVisualizada.getCusto()));
        lblVisualizarBebidaFornecedor.setText(bebidaVisualizada.getFornecedor());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bttVisualizadorBebidaFechar = new javax.swing.JButton();
        lblVisualizarBebida = new javax.swing.JLabel();
        lblVisualizarBebidaNome = new javax.swing.JLabel();
        lblVisualizarBebidaCusto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lblVisualizarBebidaFornecedor = new javax.swing.JTextArea();

        bttVisualizadorBebidaFechar.setText("Fechar");
        bttVisualizadorBebidaFechar.addActionListener(this::bttVisualizadorBebidaFecharActionPerformed);

        lblVisualizarBebida.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lblVisualizarBebida.setText("Visualizar (Bebida)");

        jLabel1.setText("Nome:");

        jLabel2.setText("Custo:");

        jLabel3.setText("Fornecedor:");

        lblVisualizarBebidaFornecedor.setColumns(20);
        lblVisualizarBebidaFornecedor.setRows(5);
        lblVisualizarBebidaFornecedor.setEnabled(false);
        lblVisualizarBebidaFornecedor.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                lblVisualizarBebidaFornecedorComponentResized(evt);
            }
        });
        jScrollPane3.setViewportView(lblVisualizarBebidaFornecedor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(bttVisualizadorBebidaFechar)
                        .addGap(75, 75, 75)
                        .addComponent(lblVisualizarBebida))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3)
                            .addComponent(lblVisualizarBebidaCusto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblVisualizarBebidaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttVisualizadorBebidaFechar)
                    .addComponent(lblVisualizarBebida))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(lblVisualizarBebidaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(lblVisualizarBebidaCusto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(120, 120, 120))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttVisualizadorBebidaFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttVisualizadorBebidaFecharActionPerformed
        BarraTarefas.setSelectedIndex(BarraTarefas.getTabCount() - 1);
        BarraTarefas.remove(this);
    }//GEN-LAST:event_bttVisualizadorBebidaFecharActionPerformed

    private void lblVisualizarBebidaFornecedorComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblVisualizarBebidaFornecedorComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_lblVisualizarBebidaFornecedorComponentResized


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttVisualizadorBebidaFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblVisualizarBebida;
    private javax.swing.JLabel lblVisualizarBebidaCusto;
    private javax.swing.JTextArea lblVisualizarBebidaFornecedor;
    private javax.swing.JLabel lblVisualizarBebidaNome;
    // End of variables declaration//GEN-END:variables
}
