/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package restaurante.view;
import restaurante.Cliente;

/**
 *
 * @author janderson
 */
public class PanelClienteMesa extends javax.swing.JPanel {

    private javax.swing.JTabbedPane BarraTarefas;
    private Cliente usuarioLogado;
    
    public PanelClienteMesa(Cliente pessoaLogada, javax.swing.JTabbedPane BarraTarefas) {
        initComponents();
        this.BarraTarefas = BarraTarefas;
        this.usuarioLogado = pessoaLogada;
        if (usuarioLogado != null) {
            TextoEscolhaMesa.setText("Excelente escolha, Cliente " + usuarioLogado.getNome());
        } else {
            TextoEscolhaMesa.setText("Excelente escolha, Cliente (Modo de Teste)");
        }
    }

    // O 'this' representa a própria classe InterfaceMesaTeste.
// O Java vai caçar onde essa classe está guardada nas abas e vai fechá-la.

//jTabbedPane1.remove(this);
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextoEscolhaMesa = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtClienteMesaEscolha = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bttClienteMesaConfirmar = new javax.swing.JButton();

        TextoEscolhaMesa.setFont(new java.awt.Font("Liberation Sans", 1, 30)); // NOI18N
        TextoEscolhaMesa.setText("Excelente escolha, (cliente)!");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel3.setText("Selecione sua mesa:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Mesas Ocupadas"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        bttClienteMesaConfirmar.setText("Confirmar");
        bttClienteMesaConfirmar.addActionListener(this::bttClienteMesaConfirmarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtClienteMesaEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bttClienteMesaConfirmar))
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(TextoEscolhaMesa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(TextoEscolhaMesa)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtClienteMesaEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bttClienteMesaConfirmar))
                        .addGap(125, 125, 125))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(96, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttClienteMesaConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttClienteMesaConfirmarActionPerformed
        PanelClientePedido novopedido = new PanelClientePedido(usuarioLogado, BarraTarefas);
        
        BarraTarefas.addTab("Novo pedido", novopedido);
        BarraTarefas.setSelectedIndex(BarraTarefas.getTabCount() - 1);
        
        BarraTarefas.remove(this);
    }//GEN-LAST:event_bttClienteMesaConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TextoEscolhaMesa;
    private javax.swing.JButton bttClienteMesaConfirmar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtClienteMesaEscolha;
    // End of variables declaration//GEN-END:variables
}
