/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package restaurante.view;

import restaurante.Administrador;

/**
 *
 * @author janderson
 */
public class PanelADMChecarHistoricos extends javax.swing.JPanel {

    private javax.swing.JTabbedPane BarraTarefas;
    private Administrador usuarioLogado;
    
    public PanelADMChecarHistoricos(Administrador pessoaLogada, javax.swing.JTabbedPane BarraTarefas) {
        initComponents();
        this.BarraTarefas = BarraTarefas;
        this.usuarioLogado = pessoaLogada;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bttADMHistoricosUsuarios = new javax.swing.JButton();
        bttADMHistoricosGeralContas = new javax.swing.JButton();
        bttADMHistoricosGeralPedidos = new javax.swing.JButton();
        bttADMHistoricosClientes = new javax.swing.JButton();
        bttADMHistoricosVoltar = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jLabel1.setText("Que histórico deseja checar hoje ?");

        bttADMHistoricosUsuarios.setText("Historico de usuários");
        bttADMHistoricosUsuarios.addActionListener(this::bttADMHistoricosUsuariosActionPerformed);

        bttADMHistoricosGeralContas.setText("Historico geral de contas");
        bttADMHistoricosGeralContas.addActionListener(this::bttADMHistoricosGeralContasActionPerformed);

        bttADMHistoricosGeralPedidos.setText("Historico geral de pedidos");
        bttADMHistoricosGeralPedidos.addActionListener(this::bttADMHistoricosGeralPedidosActionPerformed);

        bttADMHistoricosClientes.setText("Histórico de um cliente");
        bttADMHistoricosClientes.addActionListener(this::bttADMHistoricosClientesActionPerformed);

        bttADMHistoricosVoltar.setText("Voltar");
        bttADMHistoricosVoltar.addActionListener(this::bttADMHistoricosVoltarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bttADMHistoricosVoltar)
                .addGap(81, 81, 81))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bttADMHistoricosGeralContas)
                            .addComponent(bttADMHistoricosUsuarios)
                            .addComponent(bttADMHistoricosGeralPedidos)
                            .addComponent(bttADMHistoricosClientes))))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addComponent(bttADMHistoricosUsuarios)
                .addGap(57, 57, 57)
                .addComponent(bttADMHistoricosGeralContas)
                .addGap(52, 52, 52)
                .addComponent(bttADMHistoricosGeralPedidos)
                .addGap(59, 59, 59)
                .addComponent(bttADMHistoricosClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(bttADMHistoricosVoltar)
                .addGap(78, 78, 78))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttADMHistoricosVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttADMHistoricosVoltarActionPerformed
        BarraTarefas.setSelectedIndex(BarraTarefas.getTabCount() - 1);
        BarraTarefas.remove(this);
    }//GEN-LAST:event_bttADMHistoricosVoltarActionPerformed

    private void bttADMHistoricosUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttADMHistoricosUsuariosActionPerformed
        PanelADMHistoricoUsuarios historico = new PanelADMHistoricoUsuarios(usuarioLogado, BarraTarefas);
        
        BarraTarefas.addTab("Usuários", historico);
        BarraTarefas.setSelectedIndex(BarraTarefas.getTabCount() - 1);
        BarraTarefas.remove(this);
    }//GEN-LAST:event_bttADMHistoricosUsuariosActionPerformed

    private void bttADMHistoricosClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttADMHistoricosClientesActionPerformed
        PanelADMHistoricoCliente historico = new PanelADMHistoricoCliente(usuarioLogado, BarraTarefas);
        
        BarraTarefas.addTab("Históricos de clientes", historico);
        BarraTarefas.setSelectedIndex(BarraTarefas.getTabCount() - 1);
        BarraTarefas.remove(this);
    }//GEN-LAST:event_bttADMHistoricosClientesActionPerformed

    private void bttADMHistoricosGeralContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttADMHistoricosGeralContasActionPerformed
        PanelADMHistoricoContas historico = new PanelADMHistoricoContas(usuarioLogado, BarraTarefas);
        
        BarraTarefas.addTab("Históricos gerais de conta", historico);
        BarraTarefas.setSelectedIndex(BarraTarefas.getTabCount() - 1);
        BarraTarefas.remove(this);
    }//GEN-LAST:event_bttADMHistoricosGeralContasActionPerformed

    private void bttADMHistoricosGeralPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttADMHistoricosGeralPedidosActionPerformed
        PanelADMHistoricoPedidos historico = new PanelADMHistoricoPedidos(usuarioLogado, BarraTarefas);
        
        BarraTarefas.addTab("Históricos gerais de pedido", historico);
        BarraTarefas.setSelectedIndex(BarraTarefas.getTabCount() - 1);
        BarraTarefas.remove(this);
    }//GEN-LAST:event_bttADMHistoricosGeralPedidosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttADMHistoricosClientes;
    private javax.swing.JButton bttADMHistoricosGeralContas;
    private javax.swing.JButton bttADMHistoricosGeralPedidos;
    private javax.swing.JButton bttADMHistoricosUsuarios;
    private javax.swing.JButton bttADMHistoricosVoltar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
