/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package restaurante.view;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import restaurante.Cliente;
import restaurante.Cozinha;
import restaurante.Pedido;
import restaurante.Cardapio;
import restaurante.Comida;
import restaurante.Bebida;
import restaurante.Conta;

/**
 *
 * @author janderson
 */
public class PanelClientePedido extends javax.swing.JPanel {

    private javax.swing.JTabbedPane BarraTarefas;
    private Cliente usuarioLogado;
    
    public PanelClientePedido(Cliente pessoaLogada, javax.swing.JTabbedPane BarraTarefas) {
        initComponents();
        this.BarraTarefas = BarraTarefas;
        this.usuarioLogado = pessoaLogada;
        
        //Lógica de criarr novo pedido:
        if (this.usuarioLogado.getMesaAtual() != null) {
            if (this.usuarioLogado.getContaAtual() != null) {
                if (this.usuarioLogado.getPedidoAtual() == null) {
                    this.usuarioLogado.setPedidoAtual(new Pedido(usuarioLogado, usuarioLogado.getMesaAtual()));
                } else {
                    System.out.println("Ja possui um pedido aberto.");
                }
            } else {
                this.usuarioLogado.setContaAtual(new Conta(usuarioLogado, usuarioLogado.getMesaAtual().getMesaNumero()));
                this.usuarioLogado.setPedidoAtual(new Pedido(usuarioLogado, usuarioLogado.getMesaAtual())); 
                this.usuarioLogado.addHistoricoCliente(usuarioLogado.getContaAtual());
            }
        } 
        else {
            System.out.println("Escolha uma mesa primeiro.");
        }
        
        DefaultTableModel TabelaClientePedidoComida= (DefaultTableModel) tblClientePedidoComida.getModel();
        DefaultTableModel TabelaClientePedidoBebida = (DefaultTableModel) tblClientePedidoBebida.getModel();
        
        for(Comida itens : Comida.getListaComida()){
            Object[] cardapioComida = new Object[]{itens.getNome(), "$" + itens.getCusto()};
            TabelaClientePedidoComida.addRow(cardapioComida);
        }
        for(Bebida itens : Bebida.getListaBebida()){
            
            Object[] cardapioBebida = new Object[]{itens.getNome(), "$" + itens.getCusto()};
            TabelaClientePedidoBebida.addRow(cardapioBebida);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblClientePedidoAtual = new javax.swing.JTable();
        bttClientePedidoAdicionarItem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblClientePedidoComida = new javax.swing.JTable();
        bttClientePedidoFinalizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtClientePedidoQuantidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblClientePedidoTotal = new javax.swing.JLabel();
        bttClientePedidoVisualizar = new javax.swing.JToggleButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblClientePedidoBebida = new javax.swing.JTable();
        bttClientePedidoCancelar = new javax.swing.JButton();
        bttClientePedidoRemover = new javax.swing.JButton();
        bttClientePedidoAtualizar = new javax.swing.JButton();

        tblClientePedidoAtual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Quantidade", "Custo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblClientePedidoAtual);

        bttClientePedidoAdicionarItem.setText("Adicionar");
        bttClientePedidoAdicionarItem.addActionListener(this::bttClientePedidoAdicionarItemActionPerformed);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel1.setText("Selecione item que deseja adicionar ao pedido:");

        tblClientePedidoComida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Comidas", "Custo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblClientePedidoComida);

        bttClientePedidoFinalizar.setText("Finalizar");
        bttClientePedidoFinalizar.addActionListener(this::bttClientePedidoFinalizarActionPerformed);

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 30)); // NOI18N
        jLabel3.setText("Faça seu pedido!");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel4.setText("Cadápio:");

        jLabel5.setText("Quantia:");

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel6.setText("Seu pedido atual:");

        lblClientePedidoTotal.setText("Total:");

        bttClientePedidoVisualizar.setText("Visualizar");

        tblClientePedidoBebida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bebidas", "Custo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblClientePedidoBebida);

        bttClientePedidoCancelar.setText("Cancelar");
        bttClientePedidoCancelar.addActionListener(this::bttClientePedidoCancelarActionPerformed);

        bttClientePedidoRemover.setText("Remover");
        bttClientePedidoRemover.addActionListener(this::bttClientePedidoRemoverActionPerformed);

        bttClientePedidoAtualizar.setText("Atualizar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(jLabel4))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel1))
                        .addComponent(jLabel3)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(bttClientePedidoVisualizar)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtClientePedidoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(bttClientePedidoCancelar)
                                        .addComponent(bttClientePedidoAdicionarItem)
                                        .addComponent(bttClientePedidoAtualizar))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(lblClientePedidoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(bttClientePedidoFinalizar))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bttClientePedidoRemover)))))
                .addGap(0, 64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(bttClientePedidoCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(bttClientePedidoAtualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(bttClientePedidoVisualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtClientePedidoQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(bttClientePedidoAdicionarItem)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bttClientePedidoRemover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblClientePedidoTotal)
                            .addComponent(bttClientePedidoFinalizar)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttClientePedidoAdicionarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttClientePedidoAdicionarItemActionPerformed
        DefaultTableModel TabelaPedidoAtual = (DefaultTableModel) tblClientePedidoAtual.getModel();
        int comida_selecionada = tblClientePedidoComida.getSelectedRow();
        int bebida_selecionada = tblClientePedidoBebida.getSelectedRow();
        String quantidade = txtClientePedidoQuantidade.getText().trim();

        // 1. Bloqueia se o usuário não clicou em NENHUMA das duas tabelas
        if (comida_selecionada == -1 && bebida_selecionada == -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione um item de um dos cardápios.");
            return;
        }

        // 2. Bloqueia se ele tentou selecionar nas DUAS tabelas ao mesmo tempo
        if (comida_selecionada != -1 && bebida_selecionada != -1) {
            JOptionPane.showMessageDialog(this, "Por favor, selecione somente um item por vez (ou comida ou bebida).");
            tblClientePedidoBebida.clearSelection();
            tblClientePedidoComida.clearSelection();
            return;
        }   

        // 3. Valida se a quantidade é estritamente um número maior que zero
        if (quantidade.isEmpty() || !quantidade.matches("^[0-9]+$") || quantidade.equals("0")) {
            JOptionPane.showMessageDialog(this, "Por favor, insira uma quantidade válida (número inteiro maior que 0).");
            return;
        }

        // --- SE PASSOU PELAS VALIDAÇÕES, O INPUT É 100% SEGURO ---
        int qtd = Integer.parseInt(quantidade);

        // 4. Processa se foi selecionado uma Comida
        if (comida_selecionada != -1) {
            // Pega os dados da linha selecionada na tabela de Comidas (ex: coluna 0 = Nome, coluna 1 = Preço)
            String nomeComida = tblClientePedidoComida.getValueAt(comida_selecionada, 0).toString();
            double custoComida = Double.parseDouble(tblClientePedidoComida.getValueAt(comida_selecionada, 1).toString()) * qtd;
            usuarioLogado.getPedidoAtual().addTotal(custoComida);
            Object[] itemPedido = new Object[]{nomeComida, qtd, "$" + custoComida};
            TabelaPedidoAtual.addRow(itemPedido);
            tblClientePedidoComida.clearSelection();
            
        }
        // 5. Processa se foi selecionado uma Bebida
        else if (bebida_selecionada != -1) {
            String nomeBebida = tblClientePedidoBebida.getValueAt(bebida_selecionada, 0).toString();
            double custoBebida = Double.parseDouble(tblClientePedidoBebida.getValueAt(bebida_selecionada, 1).toString()) * qtd;
            usuarioLogado.getPedidoAtual().addTotal(custoBebida);
            Object[] itemPedido = new Object[]{nomeBebida, qtd, "$" + custoBebida};
            TabelaPedidoAtual.addRow(itemPedido);
            tblClientePedidoBebida.clearSelection();
        }
        
        lblClientePedidoTotal.setText("Total: $" + usuarioLogado.getPedidoAtual().getTotal());
        
        txtClientePedidoQuantidade.setText(""); // Limpa o campo de quantidade
    }//GEN-LAST:event_bttClientePedidoAdicionarItemActionPerformed

    private void bttClientePedidoFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttClientePedidoFinalizarActionPerformed
        //pega o nome do item na row, procura na lista de cardápios e adciona em cliente.pedido_atual
        if(tblClientePedidoAtual.getRowCount() != 0){
            for(int i = 0; i < tblClientePedidoAtual.getRowCount(); i++){
                String nomeItem = tblClientePedidoAtual.getValueAt(i, 0).toString();
                String quantidadeItem = tblClientePedidoAtual.getValueAt(i, 1).toString();
                
                for(Cardapio item : Cozinha.getListaProduto()){
                    if(nomeItem.equals(item.getNome())){
                        usuarioLogado.PedirNovosItens(item, quantidadeItem);
                        break;
                    }
                }
            }
            usuarioLogado.enviarPedido();
            
            PanelClientePagamentoConta conta = new PanelClientePagamentoConta(usuarioLogado, BarraTarefas);
            
            BarraTarefas.addTab("Sua conta", conta);
            BarraTarefas.setSelectedIndex(BarraTarefas.getTabCount() - 1);

            BarraTarefas.remove(this);
        }
        else{
            JOptionPane.showMessageDialog(this, "Pedido vazio, selecione algum item.");
        }
    }//GEN-LAST:event_bttClientePedidoFinalizarActionPerformed

    private void bttClientePedidoRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttClientePedidoRemoverActionPerformed
        int remover = tblClientePedidoAtual.getSelectedRow();
        if(remover != -1){
            DefaultTableModel tabelaPedidoAtual = (DefaultTableModel) tblClientePedidoAtual.getModel();
            
            
            double valor_retirado = Double.parseDouble(tblClientePedidoAtual.getValueAt(remover, 2).toString());
            
            usuarioLogado.getPedidoAtual().addTotal(-valor_retirado);
            
            lblClientePedidoTotal.setText("Total: $" + usuarioLogado.getPedidoAtual().getTotal());
            tabelaPedidoAtual.removeRow(remover);
            
        }
        else{
            JOptionPane.showMessageDialog(this, "selecione algum item que deseja remover.");
        }
    }//GEN-LAST:event_bttClientePedidoRemoverActionPerformed

    private void bttClientePedidoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttClientePedidoCancelarActionPerformed
        // Checar se existe conta possui pedidos(listapedidos.isEmpty), se existir, apaga o pedido e chama conta, se não, apaga o pedido e a conta e chama inicio.
        if(this.usuarioLogado.getContaAtual().getListaPedidosCliente().isEmpty()){
           this.usuarioLogado.getHistoricoCliente().remove(usuarioLogado.getContaAtual());
           this.usuarioLogado.setContaAtual(null);
           this.usuarioLogado.setPedidoAtual(null);
           
           BarraTarefas.setSelectedIndex(BarraTarefas.getTabCount() - 1);

           BarraTarefas.remove(this);
        } 
        else{
           PanelClientePagamentoConta conta = new PanelClientePagamentoConta(usuarioLogado, BarraTarefas);
           this.usuarioLogado.setPedidoAtual(null);
           
           BarraTarefas.addTab("Sua conta", conta);
           BarraTarefas.setSelectedIndex(BarraTarefas.getTabCount() - 1);

           BarraTarefas.remove(this);
        }
    }//GEN-LAST:event_bttClientePedidoCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttClientePedidoAdicionarItem;
    private javax.swing.JButton bttClientePedidoAtualizar;
    private javax.swing.JButton bttClientePedidoCancelar;
    private javax.swing.JButton bttClientePedidoFinalizar;
    private javax.swing.JButton bttClientePedidoRemover;
    private javax.swing.JToggleButton bttClientePedidoVisualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblClientePedidoTotal;
    private javax.swing.JTable tblClientePedidoAtual;
    private javax.swing.JTable tblClientePedidoBebida;
    private javax.swing.JTable tblClientePedidoComida;
    private javax.swing.JTextField txtClientePedidoQuantidade;
    // End of variables declaration//GEN-END:variables
}
