/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package restaurante.view;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import restaurante.Cliente;
import restaurante.Mesa;

/**
 *
 * @author janderson
 */
public class PanelClienteMesa extends javax.swing.JPanel {

    private javax.swing.JTabbedPane BarraTarefas;
    private Cliente usuarioLogado;
    
    public PanelClienteMesa(Cliente pessoaLogada, javax.swing.JTabbedPane BarraTarefas) {
        initComponents();
        this.BarraTarefas = BarraTarefas;
        this.usuarioLogado = pessoaLogada;
        
        DefaultTableModel TabelaMesasOcupadas = (DefaultTableModel) tblMesas.getModel();
        
        if (usuarioLogado != null) {
            TextoEscolhaMesa.setText("Excelente escolha, Cliente " + usuarioLogado.getNome());
        } 
        else {
            TextoEscolhaMesa.setText("Excelente escolha, Cliente (Modo de Teste)");
        }
        
        for(String ocupadas : Mesa.getListaMesa()){
            
            Object[] novaMesaOcupada = new Object[]{"Mesa " + ocupadas + " ocupada"};
            TabelaMesasOcupadas.addRow(novaMesaOcupada);
        }
    }

    //O 'this' representa a própria classe InterfaceMesaTeste.
//O Java vai caçar onde essa classe está guardada nas abas e vai fechá-la.

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextoEscolhaMesa = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtClienteMesaEscolha = new javax.swing.JTextField();
        bttClienteMesaConfirmar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMesas = new javax.swing.JTable();

        TextoEscolhaMesa.setFont(new java.awt.Font("Liberation Sans", 1, 30)); // NOI18N
        TextoEscolhaMesa.setText("Excelente escolha, (cliente)!");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel3.setText("Selecione sua mesa:");

        bttClienteMesaConfirmar.setText("Confirmar");
        bttClienteMesaConfirmar.addActionListener(this::bttClienteMesaConfirmarActionPerformed);

        tblMesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mesas ocupadas"
            }
        ));
        jScrollPane1.setViewportView(tblMesas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(TextoEscolhaMesa)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtClienteMesaEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bttClienteMesaConfirmar))
                    .addComponent(jLabel3))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(TextoEscolhaMesa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtClienteMesaEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bttClienteMesaConfirmar))
                        .addGap(125, 125, 125))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttClienteMesaConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttClienteMesaConfirmarActionPerformed

        String numero_mesa = txtClienteMesaEscolha.getText();
        
        if(numero_mesa.isEmpty() || !numero_mesa.matches("\\d+")){
            JOptionPane.showMessageDialog(this, "Digite um número de mesa válido.");
            return;
        }

        if(Integer.parseInt(numero_mesa) > Mesa.getQtdMesa() || Integer.parseInt(numero_mesa) <= 0){
            JOptionPane.showMessageDialog(this, "Mesa inválida. Escolha entre 1 e " + Mesa.getQtdMesa() + ".");
            return;
        }
        
        if(Integer.parseInt(numero_mesa) <= Mesa.getQtdMesa()){
            boolean flag_mesa = true;
            for(String ocupadas : Mesa.getListaMesa()){
                if(numero_mesa.equals(ocupadas)){
                    flag_mesa = false;
                    break;
                }
            }
            if(flag_mesa == true){
                    usuarioLogado.getMesaAtual().setMesaNumero(numero_mesa);
                    Mesa.getListaMesa().add(numero_mesa);
                    txtClienteMesaEscolha.setText("");
                    
                    PanelClientePedido novopedido = new PanelClientePedido(usuarioLogado, BarraTarefas);
                    
                    BarraTarefas.addTab("Novo pedido", novopedido);
                    BarraTarefas.setSelectedIndex(BarraTarefas.getTabCount() - 1);

                    BarraTarefas.remove(this);
            }
        }
        else{
            //erro numero de mesa excede o existente
        }
    }//GEN-LAST:event_bttClienteMesaConfirmarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TextoEscolhaMesa;
    private javax.swing.JButton bttClienteMesaConfirmar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMesas;
    private javax.swing.JTextField txtClienteMesaEscolha;
    // End of variables declaration//GEN-END:variables
}
