/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package restaurante.view;

import javax.swing.table.DefaultTableModel;
import restaurante.Administrador;
import restaurante.Cozinha;
import restaurante.Pedido;
import restaurante.Cliente;

/**
 *
 * @author janderson 
 */
public class PanelADMCozinha extends javax.swing.JPanel {

    private javax.swing.JTabbedPane BarraTarefas;
    private Administrador usuarioLogado;
    
    public PanelADMCozinha(Administrador pessoaLogada, javax.swing.JTabbedPane BarraTarefas) {
        initComponents();
        this.BarraTarefas = BarraTarefas;
        this.usuarioLogado = pessoaLogada;
        
        DefaultTableModel TabelaADMCozinha = (DefaultTableModel) tblADMCozinha.getModel();
        int cont = 0;
        
        for(Pedido pendente : Cozinha.getListaPedido()){
            if(!pendente.getStatus().equals("Entregue")){
                cont ++;
                pendente.setOrdem(cont);
                Object[] feito = new Object[]{pendente.getCliente(), pendente, pendente.calcularQtdProdutos(), pendente.getStatus(), pendente.getMesa()};

                TabelaADMCozinha.addRow(feito);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        bttADMCozinhaEntregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblADMCozinha = new javax.swing.JTable();
        bttADMCozinhaVisualizar = new javax.swing.JButton();
        bttADMCozinhaEncerrar = new javax.swing.JButton();
        bttADMCozinhaAtualizar = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel2.setText("Lista de pedidos pendentes:");

        bttADMCozinhaEntregar.setText("Entregar");
        bttADMCozinhaEntregar.addActionListener(this::bttADMCozinhaEntregarActionPerformed);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 22)); // NOI18N
        jLabel1.setText("Gerenciamento da cozinha");

        tblADMCozinha.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Itens pedidos", "Quantidade", "Status", "Mesa"
            }
        ));
        jScrollPane1.setViewportView(tblADMCozinha);

        bttADMCozinhaVisualizar.setText("Visualizar");
        bttADMCozinhaVisualizar.addActionListener(this::bttADMCozinhaVisualizarActionPerformed);

        bttADMCozinhaEncerrar.setText("Encerrar atividades");
        bttADMCozinhaEncerrar.addActionListener(this::bttADMCozinhaEncerrarActionPerformed);

        bttADMCozinhaAtualizar.setText("Atualizar");
        bttADMCozinhaAtualizar.addActionListener(this::bttADMCozinhaAtualizarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addComponent(bttADMCozinhaEncerrar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bttADMCozinhaAtualizar)
                                .addGap(87, 87, 87)
                                .addComponent(bttADMCozinhaVisualizar)
                                .addGap(88, 88, 88)
                                .addComponent(bttADMCozinhaEntregar)))
                        .addGap(73, 73, 73))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttADMCozinhaVisualizar)
                    .addComponent(bttADMCozinhaAtualizar)
                    .addComponent(bttADMCozinhaEntregar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(bttADMCozinhaEncerrar)
                .addGap(87, 87, 87))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttADMCozinhaEncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttADMCozinhaEncerrarActionPerformed
        BarraTarefas.remove(this);
        
    }//GEN-LAST:event_bttADMCozinhaEncerrarActionPerformed

    private void bttADMCozinhaAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttADMCozinhaAtualizarActionPerformed
            PanelADMCozinha atualizar = new PanelADMCozinha(usuarioLogado, BarraTarefas);
        
            BarraTarefas.addTab("Cozinha", atualizar);

            BarraTarefas.setSelectedIndex(BarraTarefas.getTabCount() - 1);
            BarraTarefas.remove(this);
    }//GEN-LAST:event_bttADMCozinhaAtualizarActionPerformed

    private void bttADMCozinhaVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttADMCozinhaVisualizarActionPerformed
        int linhaSelecionada = tblADMCozinha.getSelectedRow();
        if(linhaSelecionada != -1){
            Cliente visto = (Cliente) tblADMCozinha.getValueAt(linhaSelecionada, 0);
            Pedido visualizado = (Pedido) tblADMCozinha.getValueAt(linhaSelecionada, 1);
            
            PanelVisualizarPedidoGenerico pedidocliente = new PanelVisualizarPedidoGenerico(visto, BarraTarefas, visualizado);
            BarraTarefas.addTab("Visualizar pedido", pedidocliente);
            BarraTarefas.setSelectedIndex(BarraTarefas.getTabCount() - 1);
        }
    }//GEN-LAST:event_bttADMCozinhaVisualizarActionPerformed

    private void bttADMCozinhaEntregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttADMCozinhaEntregarActionPerformed
        DefaultTableModel TabelaADMCozinha = (DefaultTableModel) tblADMCozinha.getModel();

        int linhaSelecionada = tblADMCozinha.getSelectedRow();
        if(linhaSelecionada != -1){
            Pedido entregue = (Pedido) TabelaADMCozinha.getValueAt(linhaSelecionada, 1);
            entregue.setStatusPedido("Entregue");
            TabelaADMCozinha.removeRow(linhaSelecionada);
        }
    }//GEN-LAST:event_bttADMCozinhaEntregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttADMCozinhaAtualizar;
    private javax.swing.JButton bttADMCozinhaEncerrar;
    private javax.swing.JButton bttADMCozinhaEntregar;
    private javax.swing.JButton bttADMCozinhaVisualizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblADMCozinha;
    // End of variables declaration//GEN-END:variables
}
