/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package restaurante.view;

import javax.swing.table.DefaultTableModel; 
import restaurante.Administrador;
import restaurante.Cozinha;
import restaurante.Cardapio;
import restaurante.Comida;
import restaurante.Bebida;

/**
 *
 * @author janderson
 */
public class PanelADMCardapio extends javax.swing.JPanel {

    private javax.swing.JTabbedPane BarraTarefas;
    private Administrador usuarioLogado;
    
    public PanelADMCardapio(Administrador pessoaLogada, javax.swing.JTabbedPane BarraTarefas) {
        initComponents();
        this.BarraTarefas = BarraTarefas;
        this.usuarioLogado = pessoaLogada;
        
        for(Cardapio item : Cozinha.getListaProduto()){
            if(item instanceof Comida){
                DefaultTableModel TabelaADMCardapioComida = (DefaultTableModel) tblADMCardapioComida.getModel();
                Comida listada = (Comida) item;
                
                Object[] produto = new Object[]{listada, listada.getCusto(), listada.getDescricao(), listada.getIngredientes()};
                TabelaADMCardapioComida.addRow(produto);
            }
            else{
                DefaultTableModel TabelaADMCardapioBebida = (DefaultTableModel) tblADMCardapioBebida.getModel();
                Bebida listada = (Bebida) item;
                
                Object[] produto = new Object[]{listada, listada.getCusto(), listada.getFornecedor()};
                TabelaADMCardapioBebida.addRow(produto);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCustoComidaADM = new javax.swing.JTextField();
        txtDescComidaADM = new javax.swing.JTextField();
        bttADMBebidaADD = new javax.swing.JButton();
        txtIngredComidaADM = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNomeBebidaADM = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCustoBebidaADM = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFornBebidaADM = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bttADMRemoverGenerico = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblADMCardapioComida = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        bttADMComidaADD = new javax.swing.JButton();
        txtNomeComidaADM = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblADMCardapioBebida = new javax.swing.JTable();
        bttADMCardapioEncerrar = new javax.swing.JButton();
        bttADMVisualizarGenerico = new javax.swing.JButton();

        txtCustoComidaADM.addActionListener(this::txtCustoComidaADMActionPerformed);

        bttADMBebidaADD.setText("Adicionar Bebida");
        bttADMBebidaADD.addActionListener(this::bttADMBebidaADDActionPerformed);

        jLabel2.setText("Nome:");

        jLabel3.setText("Custo:");

        jLabel4.setText("Descrição:");

        jLabel5.setText("Ingrediente:");

        bttADMRemoverGenerico.setText("Remover item");
        bttADMRemoverGenerico.addActionListener(this::bttADMRemoverGenericoActionPerformed);

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jLabel1.setText("Aqui está o cardápio atual:");

        jLabel6.setText("Nome:");

        tblADMCardapioComida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Comida", "Custo", "Desc", "ingred"
            }
        ));
        jScrollPane1.setViewportView(tblADMCardapioComida);

        jLabel7.setText("Custo:");

        jLabel8.setText("Fornecedor:");

        bttADMComidaADD.setText("Adicionar Comida");
        bttADMComidaADD.addActionListener(this::bttADMComidaADDActionPerformed);

        txtNomeComidaADM.addActionListener(this::txtNomeComidaADMActionPerformed);

        tblADMCardapioBebida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Bebidas", "Custo", "Forn"
            }
        ));
        jScrollPane2.setViewportView(tblADMCardapioBebida);

        bttADMCardapioEncerrar.setText("Encerrar atividades");
        bttADMCardapioEncerrar.addActionListener(this::bttADMCardapioEncerrarActionPerformed);

        bttADMVisualizarGenerico.setText("Visualizar item");
        bttADMVisualizarGenerico.addActionListener(this::bttADMVisualizarGenericoActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel3))
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCustoComidaADM, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtNomeComidaADM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtIngredComidaADM, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDescComidaADM, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtCustoBebidaADM, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNomeBebidaADM, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(txtFornBebidaADM, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bttADMCardapioEncerrar))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(bttADMRemoverGenerico)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(bttADMVisualizarGenerico))))))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(bttADMComidaADD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bttADMBebidaADD)
                .addGap(101, 101, 101))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(bttADMCardapioEncerrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttADMRemoverGenerico)
                    .addComponent(bttADMVisualizarGenerico))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttADMComidaADD)
                    .addComponent(bttADMBebidaADD))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNomeComidaADM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCustoComidaADM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtDescComidaADM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtIngredComidaADM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNomeBebidaADM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCustoBebidaADM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFornBebidaADM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addContainerGap(146, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCustoComidaADMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustoComidaADMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustoComidaADMActionPerformed

    private void bttADMBebidaADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttADMBebidaADDActionPerformed
        String nome = txtNomeBebidaADM.getText();
        String custo = txtCustoBebidaADM.getText();
        String forn = txtFornBebidaADM.getText(); 
        
        if(!nome.isEmpty() || !custo.isEmpty() || !forn.isEmpty()){
                new Bebida(nome, Double.parseDouble(custo), forn);
            }
            else{
                 //erro: campos vazios
            }
    }//GEN-LAST:event_bttADMBebidaADDActionPerformed

    private void bttADMRemoverGenericoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttADMRemoverGenericoActionPerformed
        DefaultTableModel TabelaADMCardapioBebida = (DefaultTableModel) tblADMCardapioBebida.getModel();
        DefaultTableModel TabelaADMCardapioComida = (DefaultTableModel) tblADMCardapioComida.getModel();
        int linhaSelecionadaBebida = tblADMCardapioBebida.getSelectedRow(); 
        int linhaSelecionadaComida = tblADMCardapioComida.getSelectedRow(); 
        
        if(linhaSelecionadaBebida == -1 && linhaSelecionadaComida == -1){
            //erro nenhuma linha selecionada
        }
        if(linhaSelecionadaBebida != -1){
            Bebida apagada = (Bebida) TabelaADMCardapioBebida.getValueAt(linhaSelecionadaBebida, 0);
            Cozinha.getListaProduto().remove(apagada);
            Bebida.getListaBebida().remove(apagada);
            apagada = null;
            TabelaADMCardapioBebida.removeRow(linhaSelecionadaBebida);
        }
        if(linhaSelecionadaComida != -1){
            Comida apagada = (Comida) TabelaADMCardapioComida.getValueAt(linhaSelecionadaComida, 0);
            Cozinha.getListaProduto().remove(apagada);
            Comida.getListaComida().remove(apagada);
            apagada = null;
            
            TabelaADMCardapioComida.removeRow(linhaSelecionadaComida);
        }
    }//GEN-LAST:event_bttADMRemoverGenericoActionPerformed

    private void bttADMComidaADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttADMComidaADDActionPerformed
        String nome = txtNomeComidaADM.getText();
        String custo = txtCustoComidaADM.getText();
        String ingred = txtIngredComidaADM.getText();
        String desc = txtDescComidaADM.getText();
        
        if(!nome.isEmpty() || !custo.isEmpty() || !ingred.isEmpty() || !desc.isEmpty()){
                new Comida(nome, Double.parseDouble(custo), ingred, desc);
            }
            else{
                 //erro: campos vazios
            }
    }//GEN-LAST:event_bttADMComidaADDActionPerformed

    private void txtNomeComidaADMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeComidaADMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeComidaADMActionPerformed

    private void bttADMCardapioEncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttADMCardapioEncerrarActionPerformed
        BarraTarefas.remove(this);
    }//GEN-LAST:event_bttADMCardapioEncerrarActionPerformed

    private void bttADMVisualizarGenericoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttADMVisualizarGenericoActionPerformed
        DefaultTableModel TabelaADMCardapioBebida = (DefaultTableModel) tblADMCardapioBebida.getModel();
        DefaultTableModel TabelaADMCardapioComida = (DefaultTableModel) tblADMCardapioComida.getModel();
        int linhaSelecionadaBebida = tblADMCardapioBebida.getSelectedRow(); 
        int linhaSelecionadaComida = tblADMCardapioComida.getSelectedRow(); 
        
        if(linhaSelecionadaBebida == -1 && linhaSelecionadaComida == -1){
            //erro nenhuma linha selecionada
        }
        if(linhaSelecionadaBebida != -1){
            Bebida vista = (Bebida) TabelaADMCardapioBebida.getValueAt(linhaSelecionadaBebida, 0);
            PanelVisualizarCardapioBebidaGenerico pn = new PanelVisualizarCardapioBebidaGenerico(usuarioLogado, BarraTarefas, vista);
                 BarraTarefas.addTab("Visualizar Bebida", pn);
                 BarraTarefas.setSelectedIndex(BarraTarefas.getTabCount() - 1);
        }
        if(linhaSelecionadaComida != -1){
            Comida vista = (Comida) TabelaADMCardapioComida.getValueAt(linhaSelecionadaComida, 0);
            PanelVisualizarCardapioComidaGenerico pn = new PanelVisualizarCardapioComidaGenerico(usuarioLogado, BarraTarefas, vista);
                BarraTarefas.addTab("Visualizar Comida", pn);
                BarraTarefas.setSelectedIndex(BarraTarefas.getTabCount() - 1);
        }
    }//GEN-LAST:event_bttADMVisualizarGenericoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttADMBebidaADD;
    private javax.swing.JButton bttADMCardapioEncerrar;
    private javax.swing.JButton bttADMComidaADD;
    private javax.swing.JButton bttADMRemoverGenerico;
    private javax.swing.JButton bttADMVisualizarGenerico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblADMCardapioBebida;
    private javax.swing.JTable tblADMCardapioComida;
    private javax.swing.JTextField txtCustoBebidaADM;
    private javax.swing.JTextField txtCustoComidaADM;
    private javax.swing.JTextField txtDescComidaADM;
    private javax.swing.JTextField txtFornBebidaADM;
    private javax.swing.JTextField txtIngredComidaADM;
    private javax.swing.JTextField txtNomeBebidaADM;
    private javax.swing.JTextField txtNomeComidaADM;
    // End of variables declaration//GEN-END:variables
}
