/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package restaurante.view;

import restaurante.Cliente;

/**
 *
 * @author janderson
 */
public class PanelVisualizarCardapioComidaGenerico extends javax.swing.JPanel {

    private javax.swing.JTabbedPane BarraTarefas;
    private Cliente usuarioLogado;
    
    public PanelVisualizarCardapioComidaGenerico(Cliente pessoaLogada, javax.swing.JTabbedPane BarraTarefas) {
        initComponents();
        this.BarraTarefas = BarraTarefas;
        this.usuarioLogado = pessoaLogada;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVisualizarComida = new javax.swing.JTable();
        bttVisualizadorComidaFechar = new javax.swing.JButton();
        lblVisualizarComida = new javax.swing.JLabel();

        tblVisualizarComida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Custo", "Descrição", "Ingredientes"
            }
        ));
        jScrollPane1.setViewportView(tblVisualizarComida);

        bttVisualizadorComidaFechar.setText("Fechar");
        bttVisualizadorComidaFechar.addActionListener(this::bttVisualizadorComidaFecharActionPerformed);

        lblVisualizarComida.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        lblVisualizarComida.setText("Visualizar (Comida)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(bttVisualizadorComidaFechar)
                .addGap(75, 75, 75)
                .addComponent(lblVisualizarComida)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttVisualizadorComidaFechar)
                    .addComponent(lblVisualizarComida))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bttVisualizadorComidaFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttVisualizadorComidaFecharActionPerformed
        BarraTarefas.setSelectedIndex(BarraTarefas.getTabCount() - 1);
        BarraTarefas.remove(this);
    }//GEN-LAST:event_bttVisualizadorComidaFecharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttVisualizadorComidaFechar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblVisualizarComida;
    private javax.swing.JTable tblVisualizarComida;
    // End of variables declaration//GEN-END:variables
}
